"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _team_dashboard from './team-dashboard.bones.json'
import _balance_nutricional from './balance-nutricional.bones.json'
import _diario_comidas from './diario-comidas.bones.json'
import _player_dashboard_metricas from './player-dashboard-metricas.bones.json'
import _player_dashboard_nutricion from './player-dashboard-nutricion.bones.json'
import _player_dashboard_resumen from './player-dashboard-resumen.bones.json'
import _team_analytics from './team-analytics.bones.json'
import _team_config from './team-config.bones.json'
import _team_evolution from './team-evolution.bones.json'
import _team_menu from './team-menu.bones.json'
import _team_supplementation from './team-supplementation.bones.json'
import _teams_list from './teams-list.bones.json'

registerBones({
  "team-dashboard": _team_dashboard,
  "balance-nutricional": _balance_nutricional,
  "diario-comidas": _diario_comidas,
  "player-dashboard-metricas": _player_dashboard_metricas,
  "player-dashboard-nutricion": _player_dashboard_nutricion,
  "player-dashboard-resumen": _player_dashboard_resumen,
  "team-analytics": _team_analytics,
  "team-config": _team_config,
  "team-evolution": _team_evolution,
  "team-menu": _team_menu,
  "team-supplementation": _team_supplementation,
  "teams-list": _teams_list,
})
