"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _player_dashboard from './player-dashboard.bones.json'
import _team_analytics from './team-analytics.bones.json'
import _team_config from './team-config.bones.json'
import _team_dashboard from './team-dashboard.bones.json'
import _team_evolution from './team-evolution.bones.json'
import _team_menu from './team-menu.bones.json'
import _team_supplementation from './team-supplementation.bones.json'
import _teams_list from './teams-list.bones.json'

registerBones({
  "player-dashboard": _player_dashboard,
  "team-analytics": _team_analytics,
  "team-config": _team_config,
  "team-dashboard": _team_dashboard,
  "team-evolution": _team_evolution,
  "team-menu": _team_menu,
  "team-supplementation": _team_supplementation,
  "teams-list": _teams_list,
})
