"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _teams_list from './teams-list.bones.json'
import _team_dashboard from './team-dashboard.bones.json'
import _team_supplementation from './team-supplementation.bones.json'
import _team_evolution from './team-evolution.bones.json'
import _team_menu from './team-menu.bones.json'
import _team_analytics from './team-analytics.bones.json'
import _team_config from './team-config.bones.json'
import _player_dashboard_resumen_perfil from './player-dashboard-resumen-perfil.bones.json'
import _player_dashboard_resumen_diario from './player-dashboard-resumen-diario.bones.json'
import _player_dashboard_resumen_mensajes from './player-dashboard-resumen-mensajes.bones.json'
import _player_dashboard_metricas_mediciones from './player-dashboard-metricas-mediciones.bones.json'
import _player_dashboard_metricas_pesos from './player-dashboard-metricas-pesos.bones.json'
import _player_dashboard_metricas_analiticas from './player-dashboard-metricas-analiticas.bones.json'
import _player_dashboard_metricas_hidratacion from './player-dashboard-metricas-hidratacion.bones.json'
import _player_dashboard_nutricion_plan from './player-dashboard-nutricion-plan.bones.json'
import _player_dashboard_nutricion_suplementacion from './player-dashboard-nutricion-suplementacion.bones.json'
import _player_dashboard_nutricion_menu from './player-dashboard-nutricion-menu.bones.json'
import _player_dashboard_nutricion_protocolos from './player-dashboard-nutricion-protocolos.bones.json'
import _diario_comidas from './diario-comidas.bones.json'

registerBones({
  "teams-list": _teams_list,
  "team-dashboard": _team_dashboard,
  "team-supplementation": _team_supplementation,
  "team-evolution": _team_evolution,
  "team-menu": _team_menu,
  "team-analytics": _team_analytics,
  "team-config": _team_config,
  "player-dashboard-resumen-perfil": _player_dashboard_resumen_perfil,
  "player-dashboard-resumen-diario": _player_dashboard_resumen_diario,
  "player-dashboard-resumen-mensajes": _player_dashboard_resumen_mensajes,
  "player-dashboard-metricas-mediciones": _player_dashboard_metricas_mediciones,
  "player-dashboard-metricas-pesos": _player_dashboard_metricas_pesos,
  "player-dashboard-metricas-analiticas": _player_dashboard_metricas_analiticas,
  "player-dashboard-metricas-hidratacion": _player_dashboard_metricas_hidratacion,
  "player-dashboard-nutricion-plan": _player_dashboard_nutricion_plan,
  "player-dashboard-nutricion-suplementacion": _player_dashboard_nutricion_suplementacion,
  "player-dashboard-nutricion-menu": _player_dashboard_nutricion_menu,
  "player-dashboard-nutricion-protocolos": _player_dashboard_nutricion_protocolos,
  "diario-comidas": _diario_comidas,
})
