export const AI_NUTRITION_RULES = [
  '1. SEGURIDAD CLÍNICA SUPREMA (PREVALENCIA TOTAL SOBRE MENÚ DE COMEDOR Y PROTOCOLOS FIJOS): La salud y seguridad médica del jugador es la prioridad número 1 e innegociable. Respeta rigurosamente las alergias, intolerancias, aversiones y contexto médico indicados en la ficha del jugador. Jamás incluyas un alimento prohibido o conflictivo. Si el jugador tiene intolerancia o aversión a un alimento, ese alimento NUNCA debe aparecer en su menú bajo ningún concepto. Si una ingesta tiene "es_protocolo_fijo: true" o procede del menú de comedor pero contiene un alimento no tolerado (ej: merluza o gambas para intolerante a pescado, cerdo para intolerante a cerdo, gluten o lactosa): QUEDA ESTRICTAMENTE PROHIBIDO SERVIRLO. Si el menú ofrece opciones aptas, elige la opción apta; si el menú de comedor NO ofrece ninguna alternativa apta, SUSTITUYE OBLIGATORIAMENTE ese alimento por una proteína segura del catálogo (pechuga de pollo, pavo, ternera magra o huevos), adaptando el plato con total normalidad y sin escribir "X sustituido por Y". Si tiene intolerancia a la lactosa, los lácteos tradicionales están prohibidos (usa opciones sin lactosa o vegetales). PROHIBIDO escribir alimentos con 0g.',
  '2. PROTOCOLOS FIJOS Y JERARQUÍA DE PRIORIDAD: Sujeto siempre a la regla suprema de seguridad médica, respeta estrictamente el orden de prioridad para cada ingesta: 1) Si tiene "es_protocolo_fijo: true" (pauta pre-partido configurada específicamente para ese horario de partido, batido post-entreno o recuperación post-partido), respeta con máxima fidelidad la pauta de alimentos indicada. 2) Si NO hay protocolo pre-partido configurado para ese horario de partido, utiliza obligatoriamente las opciones del menú del comedor de la ciudad deportiva. 3) Si no hay menú de comedor para esa toma, utiliza las preferencias habituales del perfil del jugador. 4) Si tampoco hay preferencias habituales, genera una propuesta equilibrada de libre elección acorde a los objetivos nutricionales. Si la pauta indicada ofrece alternativas separadas por barras ("/"), selecciona una sola opción principal alternando opciones si hay más de un partido en la semana.',
  '3. MÁXIMA VARIEDAD SEMANAL Y PROHIBIDO REPETIR PROTEÍNA EN EL MISMO DÍA: En toda la semana, PROHIBIDO repetir la misma fuente de proteína en la comida y en la cena del mismo día (ej: NUNCA ternera/hamburguesa en comida y ternera/hamburguesa en cena). Si a mediodía se toma carne roja/vacuno, por la noche debe ser ave (pollo/pavo), pescado blanco/azul, marisco o huevos, y viceversa. ROTA continuamente entre todas las fuentes de proteína (ternera magra, pechuga/contramuslo de pollo, pavo, conejo, pescados blancos [merluza, dorada, lubina, lenguado, bacalao], mariscos [sepia, calamar, pulpo, gambas], pescados azules [salmón, atún, bonito, emperador], huevos y legumbres aptas). ROTA también los hidratos (arroz blanco/basmati/jazmín, arroz integral, pasta, fideos de arroz, cuscús, gnocchi, patata, boniato, avena, quinoa). PROHIBIDO servir el mismo plato o la misma combinación de proteína e hidrato en días consecutivos.',
  '4. PREFERENCIAS DEL JUGADOR CON ELEVADA VARIABILIDAD: Si el jugador expresa preferencias, respeta esa base pero no repitas preparaciones idénticas todos los días. Rota dentro de esa familia de preferencias variando los alimentos y acompañamientos afines para no caer en la monotonía.',
  '5. SELECCIÓN DE ALIMENTOS DEL CATÁLOGO OFICIAL Y CÁLCULO PRECISO: Utiliza exclusivamente los nombres oficiales del catálogo disponible (ej: "Arroz blanco", "Solomillo de ternera", "Boniato", "Pechuga de pollo", "AOVE"). Tu rol primordial es gastronómico y clínico: decidir combinaciones ricas, variadas y seguras. No te preocupes por calcular mentalmente los gramos exactos: la calculadora matemática de Nutralab ajustará los gramos al múltiplo de 5g exacto según los requerimientos del jugador.',
  '6. SOLO INGREDIENTES Y GRAMAJES APROXIMADOS (SIN MÉTODOS DE COCINADO NI "EN CRUDO"): Nombra únicamente los alimentos individuales reales del catálogo con su gramaje orientativo (ej: "Arroz blanco 150g, Pechuga de pollo 150g, Brócoli 150g, AOVE 15g"). PROHIBIDO nombrar mezclas híbridas en un solo ítem (no escribir "sepia y calamar", "merluza bacalao", "manzana y pera" ni "pollo y pavo"). PROHIBIDO añadir métodos de cocinado ("a la plancha", "al horno", "hervido") y PROHIBIDO escribir "(en crudo)".',
  '7. PROHIBIDO RELLENO NARRATIVO Y RESÚMENES NUMÉRICOS: Sin introducciones, sin verbos ("Prepara...", "Añade..."), sin resúmenes numéricos al final ("Total:", "kcal", "P:"). Directo a los alimentos y gramajes.',
  '8. VERDURAS CONCRETAS: Nombra siempre verduras específicas.',
  '9. NOTAS SEMANALES INTEGRADAS Y DÍA DE PARTIDO EXACTO: Genera en el mismo JSON exactamente 4 consejos/indicaciones clave de la semana dirigidos al jugador en segunda persona ("tú") de forma cercana y profesional (hidratación, descanso, adherencia a gramajes y pauta específica si hay partido). Respeta estrictamente el día exacto de partido indicado en el plan (ej: si el partido es en viernes, NUNCA digas "partido del sábado").',
  '10. REDACCIÓN NATURAL DEL POST-ENTRENO Y POST-PARTIDO: En días de entrenamiento normal, en la ingesta de post-entreno redacta siempre: "Batido de proteína 30g disuelto en agua" (o "Batido de proteína sin lactosa 30g disuelto en agua" si tiene intolerancia a la lactosa). En día de partido, en la ingesta post-partido redacta siempre textualmente: "Recovery y fruta". PROHIBIDO usar palabras como "scoop", "aislado de proteína scoop" o tecnicismos en inglés.',
  '11. COMIDAS CON POSTRE DE FRUTA EN CASO DE POCAS INGESTAS O ALTA CARGA DE HIDRATOS: Si el jugador tiene 2 o 3 comidas al día o la comida concentra muchos hidratos (>80g HC): no satures el plato principal con una montaña de cereal o tubérculo. Reparte los hidratos incluyendo siempre fruta fresca de postre. Toda la proteína debe provenir íntegramente del plato principal, nunca añadas yogures ni lácteos como postre en comida o cena. En el desayuno de día de partido, combina fruta con hidratos de asimilación fácil y proteína limpia, nunca solo fruta cruda.',
  '12. BASE DE HIDRATOS DE PLATO Y REGLA DE COMPATIBILIDAD (UNA SOLA BASE PRINCIPAL, PROHIBIDO COMBINAR BASES COMPITIENDO): En comidas y cenas, la base de hidratos de carbono debe ser siempre un hidrato de plato, nunca bocadillos ni pan como fuente principal. En cada comida o cena debe seleccionarse una única base principal de cereal o pasta. Queda terminantemente prohibido duplicar o combinar dos platos o fuentes de la misma categoría de cereal o pasta compitiendo como base principal en la misma toma. Sí está permitido y es compatible acompañar la base principal con fruta fresca de postre, con legumbres, con una guarnición de tubérculo o con pan como acompañamiento secundario en cantidad moderada (máximo 30-40g). Si las opciones proceden de un menú con alternativas separadas por barras ("/"), estas representan opciones de libre elección entre las que se debe elegir una sola opción principal, nunca combinar opciones alternativas de la misma categoría.',
  '13. ADECUACIÓN Y TIPICIDAD SEGÚN EL TIPO DE INGESTA (NO PLATOS DE COMIDA/CENA EN OTRAS TOMAS): Toda ingesta que no sea comida ni cena (como meriendas, desayunos, medias mañanas o recenas) debe componerse obligatoriamente de alimentos y combinaciones típicas y naturales de ese momento del día. Queda TERMINANTEMENTE PROHIBIDO asignar platos principales cocinados propios de una comida o cena (como pescados cocinados, filetes o solomillos de carne, verduras hervidas o guarniciones calientes de plato) a una merienda, desayuno o colación entrehoras. Adapta los alimentos al formato habitual de esa toma para cumplir sus macronutrientes sin distorsionar la naturaleza de la ingesta.'
];

export function buildWeeklyPromptEnvelope(payloadJson) {
  return [
    'INSTRUCCIÓN CRÍTICA:',
    'Devuelve ÚNICAMENTE un objeto JSON válido con las claves "dias" y "notas".',
    'NO incluyas texto explicativo, encabezados Markdown ni introducciones.',
    'ESTRUCTURA DE RESPUESTA OBLIGATORIA:',
    '{',
    '  "dias": {',
    '    "lunes": {',
    '      "ingestas": [',
    '        {',
    '          "nombre": "Nombre de la ingesta",',
    '          "detalle": "Alimentos y gramos exactos en crudo de forma concisa."',
    '        }',
    '      ]',
    '    },',
    '    "martes": { ... },',
    '    "miercoles": { ... },',
    '    "jueves": { ... },',
    '    "viernes": { ... },',
    '    "sabado": { ... },',
    '    "domingo": { ... }',
    '  },',
    '  "notas": [',
    '    "Consejo 1...",',
    '    "Consejo 2...",',
    '    "Consejo 3...",',
    '    "Consejo 4..."',
    '  ]',
    '}',
    '',
    'ESPECIFICACIÓN COMPLETA DEL PLAN SEMANAL EN JSON:',
    payloadJson,
  ].join('\n');
}
