
export const env = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || 'http://localhost:54321',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'anon-key',
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || 'service-role-key',
  SUPABASE_SCHEMA: process.env.SUPABASE_SCHEMA || 'teams',
  JWT_SECRET: process.env.JWT_SECRET || 'jwt-secret',
  NEXT_PUBLIC_FRONTEND_URL: process.env.NEXT_PUBLIC_FRONTEND_URL || 'https://nutralab.vercel.app',
  NUTRALAB_BACKEND_URL: process.env.NUTRALAB_BACKEND_URL || 'https://nutralab.vercel.app/api',
  VLC_FOODS_API_KEY: process.env.VLC_FOODS_API_KEY || '',
  NODE_ENV: process.env.NODE_ENV || 'development',
  OPEN_ROUTER_API: process.env.OPEN_ROUTER_API || process.env.OPENROUTER_API_KEY || process.env.AI_API_KEY || '',
  AI_MODEL: process.env.AI_MODEL || process.env.CHAT_MODEL || 'openai/gpt-6-luna-pro',
  get CHAT_MODEL() { return this.AI_MODEL; },
  get AI_API_KEY() { return this.OPEN_ROUTER_API; },
  AI_PLAN_MAX_TOKENS: Number(process.env.AI_PLAN_MAX_TOKENS) || 16000,
  AI_PLAN_THINKING_EFFORT: process.env.AI_PLAN_THINKING_EFFORT || 'low',
  ANALITICA_MAX_TOKENS: Number(process.env.ANALITICA_MAX_TOKENS) || 16000,
  BILLING_SERVICE_URL: process.env.BILLING_SERVICE_URL || 'http://localhost:3005',
  BILLING_API_KEY: process.env.BILLING_API_KEY || process.env.BILLING_TOKEN || '',
};
