export const PLAN_THEME_PRESETS = [
  {
    id: 'midnight_dark',
    name: 'Midnight Dark (Defecto)',
    description: 'Azul noche profundo con toques ámbar y teal',
    colors: {
      cardTopBg: '#254d5c',
      cardTopText: '#cad6df',
      cardBodyBg: '#101229',
      cardBodyText: '#ffffff',
      boxBg: '#151932',
      boxBorder: '#2d335a',
      itemBg: '#1d1f46',
      accentText: '#ffa94d',
      itemText: '#dee2e6',
    },
    swatches: ['#101229', '#254d5c', '#ffa94d', '#151932'],
  },
  {
    id: 'obsidian_orange',
    name: 'Obsidian & Orange',
    description: 'Negro antracita mate y naranja vibrante de alto contraste',
    colors: {
      cardTopBg: '#18181b',
      cardTopText: '#fdba74',
      cardBodyBg: '#09090b',
      cardBodyText: '#ffffff',
      boxBg: '#18181b',
      boxBorder: '#27272a',
      itemBg: '#27272a',
      accentText: '#f97316',
      itemText: '#e4e4e7',
    },
    swatches: ['#09090b', '#18181b', '#f97316', '#27272a'],
  },
  {
    id: 'emerald_health',
    name: 'Emerald Health',
    description: 'Verde bosque y menta clínica para nutrición y rendimiento',
    colors: {
      cardTopBg: '#064e3b',
      cardTopText: '#a7f3d0',
      cardBodyBg: '#062420',
      cardBodyText: '#ecfdf5',
      boxBg: '#0b3832',
      boxBorder: '#047857',
      itemBg: '#0f4941',
      accentText: '#34d399',
      itemText: '#d1fae5',
    },
    swatches: ['#062420', '#064e3b', '#34d399', '#0b3832'],
  },
  {
    id: 'ocean_blue',
    name: 'Ocean Blue Pro',
    description: 'Azul marino con acentos cian y tipografía limpia',
    colors: {
      cardTopBg: '#0c4a6e',
      cardTopText: '#bae6fd',
      cardBodyBg: '#03182b',
      cardBodyText: '#f0f9ff',
      boxBg: '#082f49',
      boxBorder: '#0369a1',
      itemBg: '#0c4a6e',
      accentText: '#38bdf8',
      itemText: '#e0f2fe',
    },
    swatches: ['#03182b', '#0c4a6e', '#38bdf8', '#082f49'],
  },
  {
    id: 'clean_light',
    name: 'Clean Light / Papel',
    description: 'Modo claro minimalista para lectura diurna o impresión',
    colors: {
      cardTopBg: '#e2e8f0',
      cardTopText: '#0f172a',
      cardBodyBg: '#f8fafc',
      cardBodyText: '#0f172a',
      boxBg: '#ffffff',
      boxBorder: '#cbd5e1',
      itemBg: '#f1f5f9',
      accentText: '#ea580c',
      itemText: '#334155',
    },
    swatches: ['#f8fafc', '#e2e8f0', '#ea580c', '#ffffff'],
  },
  {
    id: 'cyber_violet',
    name: 'Cyber Violet',
    description: 'Fondo violeta tech con acentos púrpura y magenta neón',
    colors: {
      cardTopBg: '#4c1d95',
      cardTopText: '#e9d5ff',
      cardBodyBg: '#170d2b',
      cardBodyText: '#faf5ff',
      boxBg: '#261546',
      boxBorder: '#6b21a8',
      itemBg: '#3b1c6e',
      accentText: '#c084fc',
      itemText: '#f3e8ff',
    },
    swatches: ['#170d2b', '#4c1d95', '#c084fc', '#261546'],
  },
];

export const DEFAULT_PLAN_COLORS = PLAN_THEME_PRESETS[0].colors;
