alter table teams.evoluciones
  add column if not exists altura_cm double precision,
  add column if not exists pliegue_biceps double precision,
  add column if not exists pliegue_triceps double precision,
  add column if not exists pliegue_subescapular double precision,
  add column if not exists pliegue_cresta_iliaca double precision,
  add column if not exists pliegue_supraeliaco double precision,
  add column if not exists pliegue_abdominal double precision,
  add column if not exists pliegue_pantorrilla double precision,
  add column if not exists pliegue_muslo double precision,
  add column if not exists suma_8_pliegues double precision,
  add column if not exists porcentaje_grasa_faulkner double precision,
  add column if not exists porcentaje_grasa_yuhasz double precision,
  add column if not exists peso_oseo double precision,
  add column if not exists peso_residual double precision,
  add column if not exists peso_graso double precision,
  add column if not exists peso_muscular double precision,
  add column if not exists peso_magro double precision,
  add column if not exists peso_deseable double precision,
  add column if not exists endomorfia double precision,
  add column if not exists mesomorfia double precision,
  add column if not exists ectomorfia double precision,
  add column if not exists perimetro_brazo_contraido double precision,
  add column if not exists perimetro_pantorrilla double precision,
  add column if not exists perimetro_muslo double precision;

insert into teams.evoluciones (
  jugador_id,
  fecha,
  altura_cm,
  peso_kg,
  porcentaje_grasa,
  masa_magra_kg,
  pliegue_biceps,
  pliegue_triceps,
  pliegue_subescapular,
  pliegue_cresta_iliaca,
  pliegue_supraeliaco,
  pliegue_abdominal,
  pliegue_pantorrilla,
  pliegue_muslo,
  suma_6_pliegues,
  suma_8_pliegues,
  porcentaje_grasa_faulkner,
  porcentaje_grasa_yuhasz,
  peso_oseo,
  peso_residual,
  peso_graso,
  peso_muscular,
  peso_magro,
  peso_deseable,
  endomorfia,
  mesomorfia,
  ectomorfia,
  perimetro_brazo_contraido,
  perimetro_pantorrilla,
  perimetro_muslo,
  notas
)
select
  j.id,
  coalesce(j.fecha_ultima_medicion, j.updated_at::date, j.created_at::date),
  j.altura_cm,
  j.peso_kg,
  j.porcentaje_grasa,
  j.masa_magra_kg,
  j.pliegue_biceps,
  j.pliegue_triceps,
  j.pliegue_subescapular,
  j.pliegue_cresta_iliaca,
  j.pliegue_supraeliaco,
  j.pliegue_abdominal,
  j.pliegue_pantorrilla,
  j.pliegue_muslo,
  j.suma_6_pliegues,
  j.suma_8_pliegues,
  j.porcentaje_grasa_faulkner,
  j.porcentaje_grasa_yuhasz,
  j.peso_oseo,
  j.peso_residual,
  j.peso_graso,
  j.peso_muscular,
  j.peso_magro,
  j.peso_deseable,
  j.endomorfia,
  j.mesomorfia,
  j.ectomorfia,
  j.perimetro_brazo_contraido,
  j.perimetro_pantorrilla,
  j.perimetro_muslo,
  'Migrado desde ficha de jugador'
from teams.jugadores j
where coalesce(
  j.altura_cm,
  j.peso_kg,
  j.porcentaje_grasa,
  j.masa_magra_kg,
  j.suma_6_pliegues,
  j.endomorfia,
  j.mesomorfia,
  j.ectomorfia
) is not null
on conflict (jugador_id, fecha) do update set
  altura_cm = coalesce(excluded.altura_cm, teams.evoluciones.altura_cm),
  peso_kg = coalesce(excluded.peso_kg, teams.evoluciones.peso_kg),
  porcentaje_grasa = coalesce(excluded.porcentaje_grasa, teams.evoluciones.porcentaje_grasa),
  masa_magra_kg = coalesce(excluded.masa_magra_kg, teams.evoluciones.masa_magra_kg),
  pliegue_biceps = coalesce(excluded.pliegue_biceps, teams.evoluciones.pliegue_biceps),
  pliegue_triceps = coalesce(excluded.pliegue_triceps, teams.evoluciones.pliegue_triceps),
  pliegue_subescapular = coalesce(excluded.pliegue_subescapular, teams.evoluciones.pliegue_subescapular),
  pliegue_cresta_iliaca = coalesce(excluded.pliegue_cresta_iliaca, teams.evoluciones.pliegue_cresta_iliaca),
  pliegue_supraeliaco = coalesce(excluded.pliegue_supraeliaco, teams.evoluciones.pliegue_supraeliaco),
  pliegue_abdominal = coalesce(excluded.pliegue_abdominal, teams.evoluciones.pliegue_abdominal),
  pliegue_pantorrilla = coalesce(excluded.pliegue_pantorrilla, teams.evoluciones.pliegue_pantorrilla),
  pliegue_muslo = coalesce(excluded.pliegue_muslo, teams.evoluciones.pliegue_muslo),
  suma_6_pliegues = coalesce(excluded.suma_6_pliegues, teams.evoluciones.suma_6_pliegues),
  suma_8_pliegues = coalesce(excluded.suma_8_pliegues, teams.evoluciones.suma_8_pliegues),
  porcentaje_grasa_faulkner = coalesce(excluded.porcentaje_grasa_faulkner, teams.evoluciones.porcentaje_grasa_faulkner),
  porcentaje_grasa_yuhasz = coalesce(excluded.porcentaje_grasa_yuhasz, teams.evoluciones.porcentaje_grasa_yuhasz),
  peso_oseo = coalesce(excluded.peso_oseo, teams.evoluciones.peso_oseo),
  peso_residual = coalesce(excluded.peso_residual, teams.evoluciones.peso_residual),
  peso_graso = coalesce(excluded.peso_graso, teams.evoluciones.peso_graso),
  peso_muscular = coalesce(excluded.peso_muscular, teams.evoluciones.peso_muscular),
  peso_magro = coalesce(excluded.peso_magro, teams.evoluciones.peso_magro),
  peso_deseable = coalesce(excluded.peso_deseable, teams.evoluciones.peso_deseable),
  endomorfia = coalesce(excluded.endomorfia, teams.evoluciones.endomorfia),
  mesomorfia = coalesce(excluded.mesomorfia, teams.evoluciones.mesomorfia),
  ectomorfia = coalesce(excluded.ectomorfia, teams.evoluciones.ectomorfia),
  perimetro_brazo_contraido = coalesce(excluded.perimetro_brazo_contraido, teams.evoluciones.perimetro_brazo_contraido),
  perimetro_pantorrilla = coalesce(excluded.perimetro_pantorrilla, teams.evoluciones.perimetro_pantorrilla),
  perimetro_muslo = coalesce(excluded.perimetro_muslo, teams.evoluciones.perimetro_muslo);

alter table teams.jugadores
  drop column if exists fecha_ultima_medicion,
  drop column if exists altura_cm,
  drop column if exists peso_kg,
  drop column if exists porcentaje_grasa,
  drop column if exists masa_magra_kg,
  drop column if exists pliegue_biceps,
  drop column if exists pliegue_triceps,
  drop column if exists pliegue_subescapular,
  drop column if exists pliegue_cresta_iliaca,
  drop column if exists pliegue_supraeliaco,
  drop column if exists pliegue_abdominal,
  drop column if exists pliegue_pantorrilla,
  drop column if exists pliegue_muslo,
  drop column if exists suma_6_pliegues,
  drop column if exists suma_8_pliegues,
  drop column if exists porcentaje_grasa_faulkner,
  drop column if exists porcentaje_grasa_yuhasz,
  drop column if exists peso_oseo,
  drop column if exists peso_residual,
  drop column if exists peso_graso,
  drop column if exists peso_muscular,
  drop column if exists peso_magro,
  drop column if exists peso_deseable,
  drop column if exists endomorfia,
  drop column if exists mesomorfia,
  drop column if exists ectomorfia,
  drop column if exists perimetro_brazo_contraido,
  drop column if exists perimetro_pantorrilla,
  drop column if exists perimetro_muslo;

notify pgrst, 'reload schema';
